### ISSUE TITLE
Conflicts with NPM Shrinkwrap

### ISSUE THREAD

**Issue by joncursi** [kadirahq/react-storybook#181]
After installing this package from NPM, I am running into conflicts with npm shrinkwrap.

```
$ npm shrinkwrap --dev

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.7

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: undefined /Users/jcursi/Sites/joncursi/redbird/node_modules/@kadira/.meteor-portable
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

Only way to get past this is to uninstall the package and re-install the package, and rerun the shrinkwrap command which is a pain. Any idea why this is happening?

**Comment by joncursi** [comment]
`npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'shrinkwrap',
1 verbose cli   '--dev' ]
2 info using npm@3.8.7
3 info using node@v5.11.0
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack extraneous: undefined /Users/jcursi/Sites/joncursi/redbird/node_modules/@kadira/.meteor-portable
4 verbose stack     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:101:15)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:36:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
4 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
5 verbose cwd /Users/jcursi/Sites/joncursi/redbird
6 error Darwin 15.4.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap" "--dev"
8 error node v5.11.0
9 error npm  v3.8.7
10 error Problems were encountered
10 error Please correct and try again.
10 error extraneous: undefined /Users/jcursi/Sites/joncursi/redbird/node_modules/@kadira/.meteor-portable
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by nwwells** [comment]
FWIW, I'm using `shrinkwrap` and didnt' run into anything like that. Did you try `npm prune`?

**Comment by henrytseng** [comment]
I'm also running into a similar issue.  `lodash@^3.7.0` is required by `mock-express-request@0.1.1`but it looks like we're using `lodash@^4.14.1`.  

Is not 4.14.1 > 3.7.9?  Am I missing something?  

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: lodash@^3.7.0, required by mock-express-request@0.1.1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/henry/HomeSync/CareDox/projects/caredox_api/npm-debug.log
sleepyhenry:caredox_api henry$ 

```

**Comment by arunoda** [comment]
I am sure it's fixed by now or not related to storybook.
