### ISSUE TITLE
parse failed

### ISSUE THREAD

**Issue by alexissmirnov** [kadirahq/react-storybook#23]
running  `npm run storybook` inside a react project (called graph),

getting this:

```
> graph@1.0.0 storybook /Users/alexis/workspace/graph
> start-storybook -p 9001


React Storybook started on => http://localhost:9001/

webpack built 422a8a052280c45118d6 in 8576ms
Hash: 422a8a052280c45118d6
Version: webpack 1.12.14
Time: 8576ms
            Asset     Size  Chunks             Chunk Names
  admin.bundle.js  2.08 MB       0  [emitted]  admin
preview.bundle.js  2.06 MB       1  [emitted]  preview


[...]

ERROR in multi admin
Module not found: Error: Cannot resolve module 'stack-source-map/register' in /Users/alexis/workspace/graph
 @ multi admin

ERROR in multi preview
Module not found: Error: Cannot resolve module 'stack-source-map/register' in /Users/alexis/workspace/graph
 @ multi preview

ERROR in multi preview
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /Users/alexis/workspace/graph
 @ multi preview

ERROR in ./.storybook/config.js
Module build failed: Error: Couldn't find preset "stage-2" relative to directory "/Users/alexis/workspace/graph/.storybook"
    at /Users/alexis/workspace/graph/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/alexis/workspace/graph/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/alexis/workspace/graph/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/alexis/workspace/graph/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.init (/Users/alexis/workspace/graph/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/Users/alexis/workspace/graph/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/alexis/workspace/graph/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/alexis/workspace/graph/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (/Users/alexis/workspace/graph/node_modules/babel-loader/index.js:14:22)
 @ multi preview

^C
icecream:graph alexis$
icecream:graph alexis$ cat .babelrc
{
  "presets": [
    "es2015",
    "react",
    "survivejs-kanban"
  ],
  "env": {
    "start": {
      "presets": [
        "react-hmre"
      ]
    }
  }
}
```

**Comment by arunoda** [comment]
Are you using NPM 3 or NPM 2? If it's NPM2 this will help - https://github.com/kadirahq/react-storybook/blob/master/docs/known_issues.md#potential-issues-with-npm-2

**Comment by jamby77** [comment]
Not sure if my issue is the same, but I am getting:
```
ERROR in ./src/client/app/Components/Workouts.jsx
Module parse failed: /Volumes/Macintosh HD/Sites/hacknewsreader/src/client/app/Components/Workouts.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React from "react";
| import WorkoutsList from "./WorkoutsList.jsx";
| import {bindActionCreators} from "redux";
 @ ./src/client/app/Components/Stories/Workouts.js 9:16-42
```
The component works fine when served with webpack dev server Or after processed with webpack and served via regular server. Does storybook need some configurations passed to it?
npm version is 3.2.3, webpack 1.12.14

**Comment by arunoda** [comment]
Try to use this with the latest version of storybook. Surely, we've fix this.
