### ISSUE TITLE
Backslash in the search field causes a syntax error

### ISSUE THREAD

**Issue by majapw** [kadirahq/react-storybook#245]
Accidentally hit the backslash in the `Filter` input on my storybook instance. The entire left panel errored out with the following syntax error:
```
Invalid regular expression: /\/: \ at end of pattern 
SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at RegExp (native)
    at eval (eval at 181 (http://localhost:9001/static/manager.bundle.js:595:2), <anonymous>:28:30896)
    at Array.filter (native)
    at Object.n [as storyFilter] (eval at 181 (http://localhost:9001/static/manager.bundle.js:595:2), <anonymous>:28:30848)
    at t.composer (eval at 181 (http://localhost:9001/static/manager.bundle.js:595:2), <anonymous>:28:29763)
    at Array.i (eval at 181 (http://localhost:9001/static/manager.bundle.js:595:2), <anonymous>:1:24197)
    at Object.c [as dispatch] (eval at 181 (http://localhost:9001/static/manager.bundle.js:595:2), <anonymous>:27:26968)
    at setStoryFilter (eval at 181 (http://localhost:9001/static/manager.bundle.js:595:2), <anonymous>:28:11958)
    at onChange (eval at 181 (http://localhost:9001/static/manager.bundle.js:595:2), <anonymous>:28:20845)
    at t.n (eval at 181 (http://localhost:9001/static/manager.bundle.js:595:2), <anonymous>:28:23937)
```

This can only be fixed with a refresh.

**Comment by mnmtanish** [comment]
Hi @majapw 
Just pushed `v1.29.5` with a fix. Thanks for reporting.

**Comment by majapw** [comment]
Thanks! Much appreciated.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.1 containing PR #20152 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```
