### ISSUE TITLE
Error: Cannot resolve module 'webpack-hot-middleware/client' 

### ISSUE THREAD

**Issue by Maxhodges** [kadirahq/react-storybook#279]
what is this command suppose to do? seems it removed npm from my machine

```
If you are using NPM 2, you may got some weird issues. Try to use NPM 3. Here's how to do it:

npm i -g npm@3.8.5
rm -rf node_modules
npm i
```

now i get 

```
maxMBP:blackship-design maxhodges$ npm install
bash: /usr/local/bin/npm: No such file or directory
```

**Comment by Maxhodges** [comment]
installed node, but storybook still fails

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'storybook' ]
2 info using npm@3.10.2
3 info using node@v4.4.6
4 verbose run-script [ 'prestorybook', 'storybook', 'poststorybook' ]
5 info lifecycle blackship-design@~prestorybook: blackship-design@
6 silly lifecycle blackship-design@~prestorybook: no script for prestorybook, continuing
7 info lifecycle blackship-design@~storybook: blackship-design@
8 verbose lifecycle blackship-design@~storybook: unsafe-perm in lifecycle true
9 verbose lifecycle blackship-design@~storybook: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/maxhodges/Documents/github/blackship-design/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin
10 verbose lifecycle blackship-design@~storybook: CWD: /Users/maxhodges/Documents/github/blackship-design
11 silly lifecycle blackship-design@~storybook: Args: [ '-c',
11 silly lifecycle   'start-storybook -p 9002 -s ./.meteor/local/build/programs/web.browser/app,./public' ]
12 info lifecycle blackship-design@~storybook: Failed to exec storybook script
13 verbose stack Error: blackship-design@ storybook: `start-storybook -p 9002 -s ./.meteor/local/build/programs/web.browser/app,./public`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:827:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid blackship-design@
15 verbose cwd /Users/maxhodges/Documents/github/blackship-design
16 error Darwin 15.5.0
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "storybook"
18 error node v4.4.6
19 error npm  v3.10.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error blackship-design@ storybook: `start-storybook -p 9002 -s ./.meteor/local/build/programs/web.browser/app,./public`
24 error spawn ENOENT
25 error Failed at the blackship-design@ storybook script 'start-storybook -p 9002 -s ./.meteor/local/build/programs/web.browser/app,./public'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the blackship-design package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     start-storybook -p 9002 -s ./.meteor/local/build/programs/web.browser/app,./public
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs blackship-design
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls blackship-design
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

```

**Comment by Maxhodges** [comment]
now meteor doesn't run.

**Comment by Maxhodges** [comment]
ok working now after
`sudo meteor npm install --save react react-router classnames stardust`
then reinstalled storybook under sudo too
