### ISSUE TITLE
Does not use .babelrc

### ISSUE THREAD

**Issue by gajus** [kadirahq/react-storybook#41]
My `.babelrc`:

```json
{
    "presets": [
        "es2015",
        "stage-0",
        "react"
    ]
}
```

My project tree:

```
./
├── LICENSE
├── README.md
├── package.json
├── src
│   ├── index.js
│   └── stories
│       └── player.js
└── test
    ├── mocha.opts
    └── reactYoutubePlayer.js

6 directories, 11 files
```

(`./node_modules` is excluded).

When I run `babel ./src/index.js` program works as expected (compiles code using the presets defined in the `./babelrc`).

When I run `node ./node_modules/.bin/start-storybook -p 9001`, I get an error:

```
React Storybook started on => http://localhost:9001/

webpack built eca07f0b3a93021ca496 in 1950ms
Hash: eca07f0b3a93021ca496
Version: webpack 1.12.14
Time: 1950ms
            Asset     Size  Chunks             Chunk Names
  admin.bundle.js  2.53 MB       0  [emitted]  admin
preview.bundle.js  2.69 MB       1  [emitted]  preview
chunk    {0} admin.bundle.js (admin) 900 kB [rendered]
    [0] multi admin 40 bytes {0} [built]
    (removed, not relevant)
  [312] (webpack)-hot-middleware/process-update.js 3.88 kB {1} [built]

ERROR in ./src/index.js
Module build failed: SyntaxError: /Users/gajus/Documents/dev/gajus/react-youtube-player/src/index.js: Missing class properties transform.
 */
class ReactYoutubePlayer extends React.Component {
    static stateNames = {
        '-1': 'unstarted',
        0: 'ended',
        1: 'playing',
    at File.buildCodeFrameError (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-core/lib/transformation/file/index.js:407:15)
    at NodePath.buildCodeFrameError (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-traverse/lib/path/index.js:149:26)
    at pushBody (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:254:20)
    at buildBody (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:233:10)
    at run (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-plugin-transform-es2015-classes/lib/vanilla.js:151:10)
    at PluginPass.ClassExpression (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-plugin-transform-es2015-classes/lib/index.js:63:60)
    at newFn (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-traverse/lib/visitors.js:262:19)
    at NodePath._call (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (/Users/gajus/Documents/dev/gajus/react-youtube-player/node_modules/babel-traverse/lib/context.js:152:16)
 @ ./.storybook/config.js 6:4-32
```

It appears that `start-storybook` is not using `./.babelrc`.

**Comment by gajus** [comment]
Hm. Interestingly, if I change `.babelrc` to:

```
{
    "presets": [
        "does-not-exist"
    ]
}
```

I am getting:

```
ERROR in ./.storybook/config.js
Module build failed: Error: Couldn't find preset "does-not-exist" relative to directory "/Users/gajus/Documents/dev/gajus/react-youtube-player"
```

**Comment by gajus** [comment]
Relevant versions:

```
➜  react-youtube-player git:(master) ✗ node -v
v5.10.0
➜  react-youtube-player git:(master) ✗ npm -v
3.8.3
```

**Comment by arunoda** [comment]
Could you send me your versions of:

* webpack-hot-middleware
* webpack-dev-middleware

This is the project right? Where's the `.babelrc` file?

**Comment by gajus** [comment]
Sorry, `.babelrc` is in the main directory. I did not notice that `tree` program excluded it.

There is no local version of `webpack-hot-middleware` or `webpack-dev-middleware`.

While https://github.com/gajus/react-youtube-player this is the project, I have not pushed the code using `./src` setup upstream.

I have created an issue that replicates the issue, https://github.com/gajus/react-youtube-player/tree/storybook.

**Comment by arunoda** [comment]
Got it. Will check that.

**Comment by arunoda** [comment]
I think I got the issue and will work on a fix.

**Comment by arunoda** [comment]
Check the version `1.3.0`
