### ISSUE TITLE
Button is not defined error while running the storybook

### ISSUE THREAD

**Issue by ashfaqrafi** [kadirahq/react-storybook#422]
I have gone through the article https://getstorybook.io/docs/basics/slow-start-guide and after doing all the necessary steps while I ran the npm run storybook command I encountered the error "Button is not defined
ReferenceError: Button is not defined
    at eval (webpack:///:6:5)
    at renderMain (webpack:///~/@kadira/storybook/dist/client/preview/render.js:85:31)
    at renderPreview (webpack:///~/@kadira/storybook/dist/client/preview/render.js:101:10)
    at Array.renderUI (webpack:///~/@kadira/storybook/dist/client/preview/index.js:89:26)
    at Object.dispatch (webpack:///~/redux/lib/createStore.js:186:19)
    at eval (webpack:///~/@kadira/storybook/dist/client/preview/index.js:68:16)
    at eval (webpack:///~/@kadira/storybook-channel/dist/index.js:111:21)
    at Array.forEach (native)
    at Channel._handleEvent (webpack:///~/@kadira/storybook-channel/dist/index.js:110:19)
    at PageBusTransport._handleEvent (webpack:///~/@kadira/storybook-channel-pagebus/dist/index.js:59:12)"

**Comment by ashfaqrafi** [comment]
Found the error: the Button tag which is used in the index.js file is given as "Button" but it will be "button" instead.

**Comment by mnmtanish** [comment]
Hi @ashfaqrafi 
Thanks for reporting the issue. I Just updated the docs site.

**Comment by ashfaqrafi** [comment]
thanks for the reply and doc update @mnmtanish
